### ISSUE TITLE
Release 0.6.0 version of origin.js

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#147]
## Confirm readiness
- [x] _origin-js_: Confirm js tests passing
  - `git checkout develop`
  - `git pull`
  - `npm run install:dev`
  - `npm test` (This will also test smart contracts)
  - `npm start`
- [x] _demo-dapp_: Confirm all tests passing
- [x] _demo-dapp_: Confirm it runs against remote (unlinked) origin-js
  - `git checkout develop`
  - `git pull`
  - `npm install`
  - `npm start`
- [x] _demo-dapp_: Confirm it runs against local (linked) origin-js
  - `git checkout develop`
  - `git pull`
  - `npm run install:dev`
  - `npm start`
  - Probably need to **Reset Account** on MetaMask. 
- [x] Confirm deployment accounts have eth for gas
  - `npm run deploy_checklist`
  - [x] Rinkeby ([Faucet](https://faucet.rinkeby.io/)) 
    - Public post for [0]: `https://plus.google.com/u/0/114203467826302852415/posts/F7sJZMGCbgg`
    - [x] account[0] `0x1a5c29c94d03c4c8f7414564cbd57295d61e898f`
    - [x] account[1] [`0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2`](https://rinkeby.etherscan.io/address/0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2)
  - [x] Ropsten ([Faucet](https://faucet.metamask.io/))
    - [x] account[0] `0x1a5c29c94d03c4c8f7414564cbd57295d61e898f`
    - [x] account[1] `0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2`

## Publish
- [x] _demo-dapp_: Replace git reference with version number in `package.json`
  -   ` "origin": "OriginProtocol/origin-js#develop"` --> `"origin": "0.6.0"`
  - `sed -i -e 's/OriginProtocol\/origin-js#develop/0.6.0/g' package.json`
- [x] _origin-js_ : In `package.json`, confirm version is `0.6.0` (should have been changed as part of previous release)
- [x] If contracts have changed:
  - Show diff with: `git diff master..develop contracts/contracts/`
  - `cd contracts`
  - [x] Deploy new smart contracts to Ropsten. Be sure addresses are listed in ABI files. 
    - `export ROPSTEN_MNEMONIC="<mnemonic>"`
    - `npx truffle migrate --network ropsten | tee releases/0.6.0_ropsten.log`
  - [x] Deploy new smart contracts to Rinkeby.  Be sure addresses are listed in ABI files. 
    - `export RINKEBY_MNEMONIC=$ROPSTEN_MNEMONIC`
    - `npx truffle migrate --network rinkeby | tee releases/0.6.0_rinkeby.log`
  - [ ] Migrate data from old contracts to new. (Once we get around to writing migrations!)
- [x] _origin-js_: Build origin.js (in `dist/origin.js`) -- **Not redundant:** This will bake in the new contract addresses into the contract's `.json` files. 
    - `npm run install:dev`
- [x] _demo-dapp_: Merge `develop` into `master` and push
- [x] _origin-js_: Merge `develop` into `master` and push
- [x] _origin-js_: Create new [GitHub release](https://github.com/OriginProtocol/origin-js/releases) with origin.js code,
  - [x] Version in form `v0.6.0` (This will add git tag on `master`)
  - [x] Include addresses of smart contracts in description
- [x] _demo-dapp_: Add git tag to `master` to match origin-js.
  - `git tag -a v0.6.0 -m "New release"`
- [ ] _bridge-server_: Add git tag to `master` to match origin-js.
  - `git tag -a v0.6.0 -m "New release"`
- [x] _origin-js_: [Publish to npm](https://docs.npmjs.com/cli/publish). 
  - `npm publish`
- [x] _demo-dapp_: Confirm that demo-dapp works when run alone again NPM. 
- [x] _demo-dapp_: Deploy new version of dapp to heroku (url to be determined)
- [x] _bridge-server_: merge `develop` to `master`

## Follow-up
- [x] Confirm published `origin.js` file is accessible via `code.originprotocol.com` redirect
  - https://code.originprotocol.com/origin-js/origin-v0.6.0.js
- [x] _demo-dapp_ `npm unlink origin`
- [x] _demo-dapp_: Confirm that "one-line setup & run" command works on `master` branch shown by default
- [x] _demo-dapp_: confirm its using npm package works and can find contracts
- [x] _origin-js_: Increment version number to  on `develop` to for next release
  - `git checkout develop`
  - `subl package.json`
- [x] `git push`
- [x] _demo-dapp_: Replace version number with git reference in `package.json`
  -`"origin": "0.6.0"` --> ` "origin": "OriginProtocol/origin-js#develop"`
  - `git push`
- [ ] _docs_: Review docs for needed updates. Confirm example code on playground site (jsfiddle?) still work.
- [ ] Copy this to-do list into new issue for next sprint.
- [ ] Post notice of new release on Discord

**Comment by wanderingstan** [comment]
## Rinkeby
```
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x0885b7021b73169a25dacdb895d1a028bab4791c58d8edb4df373f3123ba5209
  Migrations: 0xed747bfc08ec4f97f04278b7940acefbd8d7f4cc
Saving successful migration to network...
  ... 0x010ef25e82c54a56cf8b55527720b9e9c11fe82eda74e9d9149c1661979293be
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Running step...
  Deploying PurchaseLibrary...
  ... 0x2be7f975ba7507a67604ad519f99f56f0e45dd05f8e528fe3ad38c25e6cc7c47
  PurchaseLibrary: 0x0b3fc419df0ee2caa30b512fa098c7e0c0582d0c
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Deploying UserRegistry...
  ... 0xd8285c96e319db762b13129fe202bf28e5c0f42d47ce94ae5448deefae3d43a9
  UserRegistry: 0xa080e08a6355debebbc29b9e35d8c001ad6eb3cd
  Deploying ListingsRegistry...
  ... 0xc18d795c699d8e6d804b9e83ac2f3b2ce218667f249852cc4ed886c4d646abd2
  ListingsRegistry: 0xf9555a250a36f59c6b74aabec018b8f55da72ec4
  Deploying KeyHolderLibrary...
  ... 0xc2fc5a949183df415a9b5e7a29644689982a6cbf0a39ba5739ab75cf1485b15f
  KeyHolderLibrary: 0xb67eaa8e3044c2cfbe7a4bd9192111712db0d09b
  Linking KeyHolderLibrary to KeyHolder
  Linking KeyHolderLibrary to ClaimHolderLibrary
  Deploying ClaimHolderLibrary...
  ... 0x312336e48d659b34b5719648c8b4655255ba82ae1a07b3dc9928b4588e2c56e9
  ClaimHolderLibrary: 0x7c410ddc563cbb03f9d21fd1616c597e7c66318f
  Linking ClaimHolderLibrary to ClaimHolder
  Linking KeyHolderLibrary to ClaimHolder
  Linking ClaimHolderLibrary to ClaimHolderRegistered
  Linking KeyHolderLibrary to ClaimHolderRegistered
  Linking ClaimHolderLibrary to ClaimHolderPresigned
  Linking KeyHolderLibrary to ClaimHolderPresigned
  Linking ClaimHolderLibrary to OriginIdentity
  Linking KeyHolderLibrary to OriginIdentity
  Deploying OriginIdentity...
  ... 0x8215c58d6df2d026f86a72c84db6b8df889885dc1154e3a8777be73e9f5c45dd
  OriginIdentity: 0xc8467dc9155f9d7045ea478c85dc074aecb893c6
Saving successful migration to network...
  ... 0x7af8c2eea29e1deee826228fec79f39ba55ab2522c1a678409c25060ebfa262d
Saving artifacts...
Running migration: 3_create_sample_listings.js
  Running step...
default_account:       0x1a5c29c94d03c4c8f7414564cbd57295d61e898f
a_seller_account:      0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2
a_buyer_account:       0x47d4e5afd1624ea63cd7ace59d5dc1d87cff3bb5
another_buyer_account: 0xb7cc090637f6af85e3ed8cc623a5efe95b90b9f9
  ... 0x506f96280576400dbf5408918658a38fcf5bc6e48daf472c6d34bf14f14b0564
  ... 0x82b59071c9938df411b11c176a2874214ee01e347ff18afc9c3894fb5e57ff59
  ... 0x361456cd2d0eccdf9aab7dcf1a3e710d0a6f6c909e7ae6ec43b59d68aec287ea
  ... 0xe193bdb6da94c91a8a9da9f0fc433ee1d7199b1b44834ea9a56b13b621514f7e
  ... 0x7bd7a8539cb02b2fa2057831ce4d49868a1fce9facbcea6191075abac275607c
Saving successful migration to network...
  ... 0x8b0f922176a5dfe75cb0183e1b628d3aecf3408373114a7f2499a3de4bf64264
Saving artifacts...
Running migration: 4_add_sample_issuers.js
  Running step...
  ... 0xa81b0b0fb36b0e35a26b4f10a971cb06f78fefccf8e70629796cedf2ca87d080
  ... 0xfbb19c13527aa5d156d63f11b17d22dbee15271c1b3db5449c9fb50fb90ae72a
Saving successful migration to network...
  ... 0xa656ced07ec1236e03fcdcde4d46d548dad1b2f9a1afda95741ab6a96ed2231d
Saving artifacts...
```

## Ropsten
```
$ npx truffle migrate --network ropsten
Compiling ./contracts/Listing.sol...
Compiling ./contracts/ListingsRegistry.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Purchase.sol...
Compiling ./contracts/PurchaseLibrary.sol...
Compiling ./contracts/UserRegistry.sol...
Compiling ./contracts/identity/ClaimHolder.sol...
Compiling ./contracts/identity/ClaimHolderLibrary.sol...
Compiling ./contracts/identity/ClaimHolderPresigned.sol...
Compiling ./contracts/identity/ClaimHolderRegistered.sol...
Compiling ./contracts/identity/ClaimVerifier.sol...
Compiling ./contracts/identity/ERC725.sol...
Compiling ./contracts/identity/ERC735.sol...
Compiling ./contracts/identity/KeyHolder.sol...
Compiling ./contracts/identity/KeyHolderLibrary.sol...
Compiling ./contracts/identity/OriginIdentity.sol...
Writing artifacts to ./build/contracts

Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x0c151d67cc73d28440ad35d3f8a3948f4cb98d3c1aabefc6c383ef5325141922
  Migrations: 0xe2e32df1d7e9a921c520e2c9263b949635c864c1
Saving successful migration to network...
  ... 0x358534b78abb80847067ac61363d6211c78286b024854b61f845a68e07057a2c
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Running step...
  Deploying PurchaseLibrary...
  ... 0x687d09de5c88bc582f40fa641530ee3d4a929bde4e120292c4b4d8a5b035c923
  PurchaseLibrary: 0xe367a47c875492ed2d646d8fa06ed5dc44f74bae
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Deploying UserRegistry...
  ... 0x9b5e1ca64934b48643f6718f1c5b0f1f99016afe70b34237fbdc4e8e496d3e37
  UserRegistry: 0xd9ed0df63df8dbe53ef108de9b3c59ad0118912c
  Deploying ListingsRegistry...
  ... 0x133b7826552ec22c1a788bb85e7198ffd8d22c39650999365dfbb3da7266897a
  ListingsRegistry: 0x2861f28756e14cf0733383be8aa66ba3b65f1b4e
  Deploying KeyHolderLibrary...
  ... 0xcd5f76f87b91deb8c5a6be2108c2fa59701ee93a8aa78dae7d62fc8dd2a4d1a3
  KeyHolderLibrary: 0x8e88b51bb991fbb7f35749e87eaeb6079371ccba
  Linking KeyHolderLibrary to KeyHolder
  Linking KeyHolderLibrary to ClaimHolderLibrary
  Deploying ClaimHolderLibrary...
  ... 0x0da98fa7b5edef9ab4224c709e44e70f2d65845253cb498cf955c6598c18369e
  ClaimHolderLibrary: 0x369836ffab631d5fd1cca20b6746743e9b6459fd
  Linking ClaimHolderLibrary to ClaimHolder
  Linking KeyHolderLibrary to ClaimHolder
  Linking ClaimHolderLibrary to ClaimHolderRegistered
  Linking KeyHolderLibrary to ClaimHolderRegistered
  Linking ClaimHolderLibrary to ClaimHolderPresigned
  Linking KeyHolderLibrary to ClaimHolderPresigned
  Linking ClaimHolderLibrary to OriginIdentity
  Linking KeyHolderLibrary to OriginIdentity
  Deploying OriginIdentity...
  ... 0x88592440d3dcaedf8dd75d140395cbe8144a118d2db5ea731f279c4d7f2821f5
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  OriginIdentity: 0x788371f0976b370f435ef45303f8f7f14ee27e15
Saving successful migration to network...
  ... 0xa5771d126f1466866f24c344d028266788334026ef53b333643cdf6d19535486
Saving artifacts...
Running migration: 3_create_sample_listings.js
  Running step...
default_account:       0x1a5c29c94d03c4c8f7414564cbd57295d61e898f
a_seller_account:      0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2
a_buyer_account:       0x47d4e5afd1624ea63cd7ace59d5dc1d87cff3bb5
another_buyer_account: 0xb7cc090637f6af85e3ed8cc623a5efe95b90b9f9
  ... 0x04b4f2fcd181ca52a93b6b07d3026518895799b85b7273c41778429857de80da
  ... 0x31b4e83e0d39ce460cb7e656c40a9b2af95663ddbe0be393709db2e317ba061f
  ... 0x01263a13bbbb4bafffa03c746be0e7166d9b28fbdbe875395a971dcf90280f38
  ... 0xd0a2a981562b4314271d87a124ca1c7b9f311cca62a875dfcc3c11be34a63174
  ... 0x24d7732c10f47f4826122eaf0cce231bac51b20e123c1753fb1e9a3df434edf9
Saving successful migration to network...
  ... 0x564535b5a4d47150b6c8d3f59f1abacc0717760e767f459036fe37f2f4845521
Saving artifacts...
Running migration: 4_add_sample_issuers.js
  Running step...
  ... 0x98c8367797201eeb395775115afacacc57cf4d1c03c770b719a522306d8c8872
  ... 0x98b09e365414cf6a6143e3868ccf38f2f942ffec26549cea426e7e117ddd7411
Saving successful migration to network...
  ... 0x064841d74747e709176b708e8473f840a70603984f1f1266afe6937fda0d8ee2
Saving artifacts...
```

**Comment by wanderingstan** [comment]
@micahalcorn -- I've got everything non-DApp deployed. Let's get our final fixes in there and ship it!

**Comment by micahalcorn** [comment]
@wanderingstan do you want to check any more of these boxes and/or close this?
