### ISSUE TITLE
Test error: Error during attestation validation: Error: Invalid signature v value

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#606]
When executing `npm run test:js`, I see this error scroll by:

```
Error during attestation validation: Error: Invalid signature v value
    at exports.ecrecover (/home/travis/build/OriginProtocol/origin-js/node_modules/ethereumjs-util/dist/index.js:403:11)
    at V00_UsersAdapter._callee8$ (/home/travis/build/OriginProtocol/origin-js/src/contractInterface/users/v00_adapter.js:206:25)
    at tryCatch (/home/travis/build/OriginProtocol/origin-js/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/travis/build/OriginProtocol/origin-js/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/OriginProtocol/origin-js/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/travis/build/OriginProtocol/origin-js/src/contractInterface/users/v00_adapter.js:21:191)
    at /home/travis/build/OriginProtocol/origin-js/src/contractInterface/users/v00_adapter.js:21:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Tests seem to pass though. I suspect we're not `await`ing an async function somewhere in the user resource tests, so mocha is not detecting the error. This happens in CI too. For example:

https://travis-ci.org/OriginProtocol/origin-js/jobs/437663625#L1617

**Comment by cuongdo** [comment]
Assigning to @tyleryasaka, because he's already looking at the identity contracts
